name: Fixed Simple Workflow
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        continue-on-error: true

      - name: Simple Test Execution
        continue-on-error: true
        run: |
          nix-shell -p curl --run 'curl -s ifconfig.me > branch-ip.txt'
          nix-shell -p coreutils --run 'date > branch-timestamp.txt'

      - name: Ubuntu Fallback
        if: failure()
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y curl
          curl -s ifconfig.me > fallback-ip.txt

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: branch-results
          path: "*.txt"
          retention-days: 1